In [1]:
import numpy as np

In [2]:
a = np.random.randint(10, size = (2, 3)) 
b = np.random.randint(10, size = (2, 3))

In [3]:
a

array([[8, 3, 5],
       [3, 1, 4]])

In [4]:
b

array([[6, 6, 4],
       [6, 1, 6]])

In [5]:
(a, b )

(array([[8, 3, 5],
        [3, 1, 4]]), array([[6, 6, 4],
        [6, 1, 6]]))

In [6]:
np.concatenate((a,b) , axis = 0)

array([[8, 3, 5],
       [3, 1, 4],
       [6, 6, 4],
       [6, 1, 6]])

In [7]:
np.concatenate((a,b) , axis = 1)

array([[8, 3, 5, 6, 6, 4],
       [3, 1, 4, 6, 1, 6]])

In [9]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])
x,y

(array([[1, 2, 3],
        [4, 5, 6]]), array([[ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]))

In [10]:
np.concatenate([x,y] , axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [11]:
np.concatenate([x,y] , axis = 1)

ValueError: ignored

In [12]:
m = np.arange(20).reshape(5, 4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [13]:
np.split(m,[1,3], axis =0)

[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [14]:
np.split(m,[1,3], axis =1)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]), array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]), array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [15]:
np.vsplit(m,[1,3])

[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [17]:
np.hsplit(m, [3])

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14],
        [16, 17, 18]]), array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [18]:
v = np.array([2, 1, 4, 3, 5])
v

array([2, 1, 4, 3, 5])

In [19]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [22]:
v.sort()
v

array([1, 2, 3, 4, 5])

In [24]:
twoD = np.random.randint(5, 100, (3, 3))
twoD

array([[98, 30, 98],
       [27, 81, 59],
       [63,  9, 64]])

In [25]:
np.sort(twoD, axis= 0)

array([[27,  9, 59],
       [63, 30, 64],
       [98, 81, 98]])

In [26]:
np.sort(twoD, axis= 1)

array([[30, 98, 98],
       [27, 59, 81],
       [ 9, 63, 64]])

In [27]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
arr_2d[1][1]

25

In [29]:
type(arr_2d[1][1])

numpy.int64

In [30]:
print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [34]:
arr_2d[1:][1]

array([35, 40, 45])

In [32]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [33]:
arr_2d[2:,:2]

array([[35, 40]])

In [36]:
arr_2d[1][1]= 55
arr_2d

array([[ 5, 10, 15],
       [20, 55, 30],
       [35, 40, 45]])

In [39]:
arr_2d[1][1]= 5.5
arr_2d

array([[ 5, 10, 15],
       [20,  5, 30],
       [35, 40, 45]])

In [40]:
arr_2d[1,1]=True
arr_2d

array([[ 5, 10, 15],
       [20,  1, 30],
       [35, 40, 45]])

In [42]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

birden fazla istek girersek liste şeklinde yazılır

In [43]:
v[1]

3

In [44]:
v[3]

9

In [46]:
index_list=[1,3,7]
v[index_list]

array([ 3,  9, 21])

In [47]:
v[[1,3,7]]

array([ 3,  9, 21])

In [49]:
arr2d = np.zeros((10, 10), dtype=int) 

arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [50]:
arr2d.shape

(10, 10)

In [51]:
arr2d.shape[0]

10

In [52]:
for i in range(arr2d.shape[0]) :
  arr2d[i] = i

In [53]:
arr2d[[2,4,8]]

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [54]:
arr2d[[3,4,8,7,1]]

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [59]:
jj = np.arange(1, 17).reshape(4,4)
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [58]:
jj[2,3]

12

In [61]:
jj[[1,2], [0,3]]

array([ 5, 12])

In [62]:
jj[[1,2], [0,3,1]]

IndexError: ignored

In [63]:
jj[[1,2,0], [0,3,1]]

array([ 5, 12,  2])

In [64]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [68]:
jj[[1,1],[1,3]]

array([6, 8])

In [67]:
jj[1, [1,3]]

array([6, 8])

In [69]:
jj[ : , [1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [72]:
jj[1:3, [1,3]]

array([[ 6,  8],
       [10, 12]])

In [74]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [76]:
condition = arr > 4

In [77]:
arr[condition]

array([ 5,  6,  7,  8,  9, 10])

In [78]:
arr[arr<6]

array([1, 2, 3, 4, 5])

In [80]:
arr[(arr != 3) & (arr !=4)]

array([ 1,  2,  5,  6,  7,  8,  9, 10])

In [83]:
arr[(arr<3)| (arr > 8) & ((arr != 9 )& (arr != 2))]

array([ 1,  2, 10])

In [84]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
arr[:5] = 77
arr

array([77, 77, 77, 77, 77,  6,  7,  8,  9, 10])

In [88]:
a = [0, 2, 4, 6, 8, 10]
a

[0, 2, 4, 6, 8, 10]

In [89]:
a[0:3] = 100

TypeError: ignored

In [91]:
a[0:3] = 100, 100,100
a

[100, 100, 100, 6, 8, 10]

In [92]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
slice_of_arr = arr[0:6]

In [94]:
slice_of_arr

array([1, 2, 3, 4, 5, 6])

In [95]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [96]:
arr

array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [98]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [99]:
arr_copy[:6] = [0,1,2,3,4,5]
arr_copy

array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10])

In [100]:
arr

array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [101]:
import warnings
warnings.filterwarnings('ignore')

In [102]:
np.mod(arr[arr > 3],2)

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 0])

In [103]:
x1 = np.arange(9.0).reshape(3, 3)
x2 = np.arange(3.0)

In [104]:
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [105]:
x2

array([0., 1., 2.])

In [106]:
np.subtract(x1,x2)

array([[0., 0., 0.],
       [3., 3., 3.],
       [6., 6., 6.]])

In [108]:
v = np.array([1,1,2,2,3,3,3])

In [110]:
np.mean(v)

2.142857142857143

In [111]:
arry = np.array([4,7,1,9,1,2,6,8,10])

In [113]:
np.median(arry)

6.0

In [115]:
arry = np.sort(arry)
arry

array([ 1,  1,  2,  4,  6,  7,  8,  9, 10])

In [116]:
v.std()

0.8329931278350429

In [117]:
v.var()

0.6938775510204082

In [119]:
v.sum()

15

In [120]:
np.ptp(v)

2

In [124]:
np.random.seed(42)
xarr = np.random.randn(3,5)
xarr

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337],
       [-0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783]])

<a id="5"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>